### ISSUE TITLE
Blue bug 03

### ISSUE THREAD

**Issue by anna03test** [OrganizationSOB/DemoRepo#10]

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Contract address: [0x90e56557a5efdbfff2d1a7f7c433e94b6ec7b5cb](https://etherscan.io/address/0x90e56557a5efdbfff2d1a7f7c433e94b6ec7b5cb)
![QR Code](https://openbounty.status.im/qr/OrganizationSOB/DemoRepo/bounty/10/b2bb8db63723efd3186109d6f5e863d293860ec6d1ce67318010d7f0a0466b0a/qr.png)
Network: Mainnet
To claim this bounty sign up at [https://openbounty.status.im](https://openbounty.status.im)
To fund it, send ETH or ERC20/ERC223 tokens to the contract address.
