### ISSUE TITLE
Yellow bug 04

### ISSUE THREAD

**Issue by anna03test** [OrganizationSOB/DemoRepo#11]

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Contract address: [0x8470e71bbe0fd833b3908cb2a8069eaebab80c15](https://etherscan.io/address/0x8470e71bbe0fd833b3908cb2a8069eaebab80c15)
![QR Code](https://openbounty.status.im/qr/OrganizationSOB/DemoRepo/bounty/11/24d1caf02423c7275b1603982688cdbc5330d1d6f1cd2ad4e390e7e4fbc17ec0/qr.png)
Network: Mainnet
To claim this bounty sign up at [https://openbounty.status.im](https://openbounty.status.im)
To fund it, send ETH or ERC20/ERC223 tokens to the contract address.
