### ISSUE TITLE
Get some tokens for fixing me

### ISSUE THREAD

**Issue by anna03test** [OrganizationSOB/DemoRepo#3]

**Comment by status-open-bounty** [comment]
Balance: 0.0000 ETH
Tokens: SNT: 0.00
Contract address: [0x7d61c06ee6f933d9d697f7030d3bcca448a0fa69](https://etherscan.io/address/0x7d61c06ee6f933d9d697f7030d3bcca448a0fa69)
Network: Mainnet
Paid to: annadanchenko
