### ISSUE TITLE
Demo issue for getting bounties

### ISSUE THREAD

**Issue by anna03test** [OrganizationSOB/DemoRepo#5]

**Comment by status-open-bounty** [comment]
Balance: 0.0000 ETH
Tokens: SNT: 0.00
Contract address: [0x908e1e4e6e4b185e41add0b73e68455054a2a1c5](https://etherscan.io/address/0x908e1e4e6e4b185e41add0b73e68455054a2a1c5)
Network: Mainnet
Paid to: annadanchenko
