### ISSUE TITLE
Green bug 01

### ISSUE THREAD

**Issue by anna03test** [OrganizationSOB/DemoRepo#8]

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Contract address: [0x26f895318c920e80da4a83cc534719fa9ba1d6bf](https://etherscan.io/address/0x26f895318c920e80da4a83cc534719fa9ba1d6bf)
![QR Code](https://openbounty.status.im/qr/OrganizationSOB/DemoRepo/bounty/8/b1bc87e7adb99742172f7972f12902db992fcd4605ef16330f483bca38435640/qr.png)
Network: Mainnet
To claim this bounty sign up at [https://openbounty.status.im](https://openbounty.status.im)
To fund it, send ETH or ERC20/ERC223 tokens to the contract address.
