### ISSUE TITLE
Red bug 02

### ISSUE THREAD

**Issue by anna03test** [OrganizationSOB/DemoRepo#9]

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Contract address: [0xbdc6d73c4689e1fe1459d6b076c3bfddedc28e76](https://etherscan.io/address/0xbdc6d73c4689e1fe1459d6b076c3bfddedc28e76)
![QR Code](https://openbounty.status.im/qr/OrganizationSOB/DemoRepo/bounty/9/1d69c3cac9436b0657070dae0ee7c9f210acfbf6ffb7c2c2d269301668a8e761/qr.png)
Network: Mainnet
To claim this bounty sign up at [https://openbounty.status.im](https://openbounty.status.im)
To fund it, send ETH or ERC20/ERC223 tokens to the contract address.
